export const GUIDE_CONFIG_MAX_BYTES = 51_200;
export const ASSISTANT_MAX_MESSAGE_CHARS = 500;
export const ASSISTANT_GUEST_RATE_LIMIT = 20;
export const ASSISTANT_GUEST_RATE_LIMIT_MS = 3_600_000;
export const GUIDE_CHAT_MOBILE_BOTTOM_OFFSET = '4rem';
